#!/usr/bin/env node
// Maintainer-run script — NOT part of `npm install` or `npm run build`.
//
// misp-iconify (https://github.com/MISP/misp-iconify) has no package.json
// and can't be an npm dependency as-is (tested directly: `npm install
// github:MISP/misp-iconify` fails with ENOENT ... Could not read
// package.json). It's vendored instead as a git submodule at
// packages/misp/vendor/misp-iconify, pinned to a specific commit — a
// refresh is `git submodule update --remote` (or checkout a different
// commit) followed by re-running this script, a deliberate, reviewable
// diff, never something that happens on someone else's `npm install`.
//
// Delivery mechanism: inline SVG via Pivotick's `NodeStyle.svgIcon`, NOT
// CSS classes. An earlier version of this script shipped misp-iconify's
// own icons.css (a `mask-image` + `iconClass` technique) — that doesn't
// actually render anything in Pivotick: NodeDrawer.ts's `iconClass`
// handling resolves the class through `faGlyph()` (a Font Awesome glyph
// lookup) and falls back to a hollow-square text glyph for anything else,
// which is not what misp-iconify's classes are. `svgIcon`, by contrast,
// is handled by literally injecting the markup as a real, correctly-sized
// `<svg>` element — verified against Pivotick's actual renderer source
// (NodeDrawer.ts), not assumed. So: read misp-iconify's raw source SVGs
// (src/svg/{attributes,objects,galaxies,simple}/<key>.svg — the *unframed*
// variants; `objects-framed`/`galaxies-orbit`/`hexagone` bake in their own
// border, which would double up with the border Pivotick's own `shape`
// style already draws), lightly minify them, and inline them directly
// into a generated TS file. No stylesheet needed at all.
//
// packages/misp/styles.json is deliberately NOT touched by this script —
// it's the hand-maintained "shape/color per category" policy (event, tag,
// attribute, object, galaxyCluster). This script only supplies which SVG
// exists for which specific key; styles.json says what a category should
// look like.
//
// Usage: node packages/misp/scripts/sync-icons.mjs
// (requires the submodule checked out: `git submodule update --init`)

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pkgDir = path.join(__dirname, '..')
const submoduleDir = path.join(pkgDir, 'vendor', 'misp-iconify')
const svgDir = path.join(submoduleDir, 'src', 'svg')
const srcDir = path.join(pkgDir, 'src', 'shared')

const submoduleCommit = execFileSync('git', ['-C', submoduleDir, 'rev-parse', 'HEAD']).toString().trim()

const attribution = readFileSync(path.join(submoduleDir, 'ATTRIBUTION.md'), 'utf8')
writeFileSync(
  path.join(pkgDir, 'ATTRIBUTION.md'),
  `<!-- Copied by scripts/sync-icons.mjs from misp-iconify@${submoduleCommit} — do not edit by hand. -->\n${attribution}`,
)
console.log('  vendored ATTRIBUTION.md')

// Conservative minification: drop the XML prolog, comments, and the
// (often large) Inkscape/Sodipodi editor-metadata block, then collapse
// whitespace between tags. Deliberately does NOT touch `id` attributes —
// ~80 of these icons use clip-path/mask/<use> referencing them internally.
function minifySvg(raw) {
  return raw
    .replace(/<\?xml[^>]*\?>/, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<sodipodi:namedview\b[^>]*(?:\/>|>[\s\S]*?<\/sodipodi:namedview>)/g, '')
    .replace(/>\s+</g, '><')
    .trim()
}

function readCategory(dirName) {
  const dir = path.join(svgDir, dirName)
  const icons = {}
  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.svg')) continue
    const key = file.slice(0, -'.svg'.length)
    icons[key] = minifySvg(readFileSync(path.join(dir, file), 'utf8'))
  }
  return icons
}

const attributeIcons = readCategory('attributes')
const objectIcons = readCategory('objects')
const galaxyIcons = readCategory('galaxies')
const genericIcons = readCategory('simple')

const toEntries = (icons) => JSON.stringify(icons, null, 2)

writeFileSync(
  path.join(srcDir, 'icons.generated.ts'),
  `/* eslint-disable */
// AUTO-GENERATED by scripts/sync-icons.mjs from vendor/misp-iconify's
// src/svg/{attributes,objects,galaxies,simple}/ (pinned at
// ${submoduleCommit}) — do not edit by hand. Re-run the script (after
// updating the submodule) to refresh. Double-quoted strings below are
// JSON.stringify output, not a style violation — see eslint-disable.
//
// One inline SVG string per icon key misp-iconify ships, split by
// category (which also doubles as "does an icon exist for this key" —
// see mispIconStyle.ts). Keys match this converter's entityType strings:
// bare for attribute/generic, "objects/<key>" / "galaxies/<key>" for the
// other two (the prefix is stripped here since that's how misp-iconify's
// own filenames are organized).

export const MISP_ATTRIBUTE_ICONS: Readonly<Record<string, string>> = ${toEntries(attributeIcons)}

export const MISP_OBJECT_ICONS: Readonly<Record<string, string>> = ${toEntries(objectIcons)}

export const MISP_GALAXY_ICONS: Readonly<Record<string, string>> = ${toEntries(galaxyIcons)}

export const MISP_GENERIC_ICONS: Readonly<Record<string, string>> = ${toEntries(genericIcons)}
`,
)
console.log(
  `  vendored src/shared/icons.generated.ts (${Object.keys(attributeIcons).length} attribute, ${Object.keys(objectIcons).length} object, ${Object.keys(galaxyIcons).length} galaxy, ${Object.keys(genericIcons).length} generic icons)`,
)

console.log('Done.')
