#!/usr/bin/env node
// Maintainer-run script — NOT part of `npm install` or `npm run build`.
//
// misp-iconify (https://github.com/MISP/misp-iconify) has no package.json
// and can't be an npm dependency as-is (tested directly: `npm install
// github:MISP/misp-iconify` fails with ENOENT ... Could not read
// package.json). It's vendored instead as a git submodule at
// packages/misp/vendor/misp-iconify, pinned to a specific commit — a
// refresh is `git submodule update --remote` (or checkout a different
// commit) followed by re-running this script, a deliberate, reviewable
// diff, never something that happens on someone else's `npm install`.
//
// This script reads the submodule's *already-generated* icons.css and
// icons.json (misp-iconify commits its own build output — we don't need
// its own build tooling or its nested submodules), and:
//   1. copies icons.css into packages/misp/assets/ (committed, shipped as
//      the package's "./icons.css" export — see docs/icons-and-styling.md)
//   2. parses icons.css itself for which icon keys actually exist and
//      which "frame" class(es) each one ships (misp-attributes /
//      misp-objects / misp-galaxies / misp-simple / misp-hexagone) —
//      parsing the CSS rather than trusting icons.json's `source` field
//      to guess categories, since that's the real ground truth
//   3. writes that as packages/misp/src/icons.generated.ts, a set of key
//      lookups consumed by mispIconClass.ts at runtime
//   4. copies the submodule's own ATTRIBUTION.md, which already lists
//      every icon's upstream source/license
//
// Usage: node packages/misp/scripts/sync-icons.mjs
// (requires the submodule checked out: `git submodule update --init`)

import { execFileSync } from 'node:child_process'
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pkgDir = path.join(__dirname, '..')
const submoduleDir = path.join(pkgDir, 'vendor', 'misp-iconify')
const assetsDir = path.join(pkgDir, 'assets')
const srcDir = path.join(pkgDir, 'src')

mkdirSync(assetsDir, { recursive: true })

const iconsCssSrc = path.join(submoduleDir, 'exports', 'css', 'icons.css')
copyFileSync(iconsCssSrc, path.join(assetsDir, 'icons.css'))
console.log('  vendored assets/icons.css')

const submoduleCommit = execFileSync('git', ['-C', submoduleDir, 'rev-parse', 'HEAD']).toString().trim()
const attribution = readFileSync(path.join(submoduleDir, 'ATTRIBUTION.md'), 'utf8')
writeFileSync(
  path.join(pkgDir, 'ATTRIBUTION.md'),
  `<!-- Copied by scripts/sync-icons.mjs from misp-iconify@${submoduleCommit} — do not edit by hand. -->\n${attribution}`,
)
console.log('  vendored ATTRIBUTION.md')

// Each icon key gets one or more `.misp-icon-<key>.misp-<frame>` rules.
// <key> here is the *base* name — misp-iconify strips the `objects/` /
// `galaxies/` category prefix in the actual class name (e.g. the
// `objects/ip-port` icon.json key becomes `.misp-icon-ip-port.misp-objects`,
// not `.misp-icon-objects/ip-port...`).
const css = readFileSync(iconsCssSrc, 'utf8')
const framesByBase = new Map()
for (const [, base, frame] of css.matchAll(/\.misp-icon-([a-zA-Z0-9_-]+)\.(misp-[a-zA-Z]+)/g)) {
  if (!framesByBase.has(base)) framesByBase.set(base, new Set())
  framesByBase.get(base).add(frame)
}

const objectKeys = new Set()
const galaxyKeys = new Set()
const attributeKeys = new Set()
const genericKeys = new Set()
for (const [base, frames] of framesByBase) {
  if (frames.has('misp-objects')) objectKeys.add(base)
  if (frames.has('misp-galaxies')) galaxyKeys.add(base)
  if (frames.has('misp-attributes')) attributeKeys.add(base)
  if (frames.has('misp-simple') || frames.has('misp-hexagone')) genericKeys.add(base)
}

const toArrayLiteral = (set) => JSON.stringify([...set].sort())

writeFileSync(
  path.join(srcDir, 'icons.generated.ts'),
  `/* eslint-disable */
// AUTO-GENERATED by scripts/sync-icons.mjs from vendor/misp-iconify's
// exports/css/icons.css (pinned at ${submoduleCommit}) — do not edit by
// hand. Re-run the script (after updating the submodule) to refresh.
// Double-quoted string literals below are JSON.stringify output, not a
// style violation — see eslint-disable.
//
// Which icon-key sets exist, split by the CSS "frame" class misp-iconify
// ships for them: object/galaxy cluster icons only get the .misp-objects /
// .misp-galaxies frame; attribute-type icons get .misp-attributes;
// everything else (event, tag, ...) gets .misp-simple / .misp-hexagone —
// see mispIconClass.ts for how these combine into an iconClass string.

export const MISP_OBJECT_ICON_KEYS: ReadonlySet<string> = new Set(${toArrayLiteral(objectKeys)})
export const MISP_GALAXY_ICON_KEYS: ReadonlySet<string> = new Set(${toArrayLiteral(galaxyKeys)})
export const MISP_ATTRIBUTE_ICON_KEYS: ReadonlySet<string> = new Set(${toArrayLiteral(attributeKeys)})
export const MISP_GENERIC_ICON_KEYS: ReadonlySet<string> = new Set(${toArrayLiteral(genericKeys)})
`,
)
console.log(
  `  vendored src/icons.generated.ts (${objectKeys.size} object, ${galaxyKeys.size} galaxy, ${attributeKeys.size} attribute, ${genericKeys.size} generic keys)`,
)

console.log('Done.')
