#!/usr/bin/env node
// Regenerates packages/misp/src/icons.ts from the vendored misp-iconify
// submodule (packages/misp/vendor/misp-iconify). Pivotick's node renderer
// expects raw SVG markup as a string (`style.svgIcon`), not a URL, so icons
// get baked into committed TS source rather than referenced as file paths —
// keeps packages/misp consumable with zero build step.
//
// Re-run after `git submodule update` and after adding an entry to ICONS
// below, then commit the resulting src/icons.ts diff.

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const mispDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const iconifyDir = path.join(mispDir, 'vendor', 'misp-iconify', 'src', 'svg')
const outFile = path.join(mispDir, 'src', 'icons.ts')

// icon name -> path relative to misp-iconify/src/svg
const ICONS = {
  event: 'simple/event.svg'
}

const entries = Object.entries(ICONS).map(([name, relativePath]) => {
  const svg = readFileSync(path.join(iconifyDir, relativePath), 'utf8').trim()
  return `  ${JSON.stringify(name)}: ${JSON.stringify(svg)}`
})

const content = `// Generated by packages/misp/scripts/sync-icons.mjs from the vendored
// misp-iconify submodule — do not edit by hand, re-run the script instead.

export const MISP_ICONS: Record<string, string> = {
${entries.join(',\n')}
}
`

writeFileSync(outFile, content)
console.log(`Wrote ${outFile} with ${Object.keys(ICONS).length} icon(s)`)
